# Generated by Django 4.2.4 on 2023-08-16 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wbmode', models.CharField(blank=True, choices=[(0, 'Off'), (1, 'auto'), (2, 'incandescent'), (3, 'fluorescent'), (4, 'warm-fluorescent'), (5, 'daylight'), (6, 'cloudy-daylight'), (7, 'twilight'), (8, 'shade'), (9, 'manual')], max_length=50, null=True)),
                ('saturation', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
                ('sensor_id', models.IntegerField(choices=[(0, 0), (1, 1)])),
                ('exposuretime', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(34000), django.core.validators.MaxValueValidator(358733000)])),
                ('gain', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('ispdigitalgain', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('tnr_mode', models.CharField(choices=[(0, 'NoiseReduction_Off'), (1, 'NoiseReduction_Fast'), (2, 'NoiseReduction_HighQuality')], default='NoiseReduction_Fast', max_length=50)),
                ('ee_mode', models.CharField(choices=[(0, 'EdgeEnhancement_Off'), (1, 'EdgeEnhancement_Fast'), (2, 'EdgeEnhancement_HighQuality')], default='EdgeEnhancement_Fast', max_length=50)),
                ('aeantibanding', models.CharField(choices=[(0, 'AeAntibandingMode_Off'), (1, 'AeAntibandingMode_Auto'), (2, 'AeAntibandingMode_50HZ'), (3, 'AeAntibandingMode_60HZ')], default='AeAntibandingMode_Auto', max_length=50)),
                ('exposurecompensation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)])),
                ('aelock', models.BooleanField(default=False)),
                ('awblock', models.BooleanField(default=False)),
            ],
        ),
    ]
