# Generated by Django 4.2.4 on 2023-08-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandsmodel',
            name='aeantibanding',
            field=models.CharField(choices=[('AEANTIBANDINGMODE_OFF', 'AeAntibandingMode_Off'), ('AEANTIBANDINGMODE_AUTO', 'AeAntibandingMode_Auto'), ('AEANTIBANDINGMODE_50HZ', 'AeAntibandingMode_50HZ'), ('AEANTIBANDINGMODE_60HZ', 'AeAntibandingMode_60HZ')], default='AeAntibandingMode_Auto', max_length=50),
        ),
        migrations.AlterField(
            model_name='commandsmodel',
            name='ee_mode',
            field=models.CharField(choices=[('EDGEENHANCEMENT_OFF', 'EdgeEnhancement_Off'), ('EDGEENHANCEMENT_FAST', 'EdgeEnhancement_Fast'), ('EDGEENHANCEMENT_HIGHQUALITY', 'EdgeEnhancement_HighQuality')], default='EdgeEnhancement_Fast', max_length=50),
        ),
        migrations.AlterField(
            model_name='commandsmodel',
            name='tnr_mode',
            field=models.CharField(choices=[('NOISEREDUCTION_OFF', 'NoiseReduction_Off'), ('NOISEREDUCTION_FAST', 'NoiseReduction_Fast'), ('NOISEREDUCTION_HIGHQUALITY', 'NoiseReduction_HighQuality')], default='NoiseReduction_Fast', max_length=50),
        ),
        migrations.AlterField(
            model_name='commandsmodel',
            name='wbmode',
            field=models.CharField(blank=True, choices=[('OFF', 'Off'), ('AUTO', 'auto'), ('INCANDESECENT', 'incandescent'), ('FLUORESCENT', 'fluorescent'), ('WARM_FLUORESCENT', 'warm-fluorescent'), ('DAYLIGHT', 'daylight'), ('CLOUDY_DAYLIGHT', 'cloudy-daylight'), ('TWILIGHT', 'twilight'), ('SHADE', 'shade'), ('MANUAL', 'manual')], max_length=50, null=True),
        ),
    ]
